Importando librería numpy

In [ ]:
import numpy as np

Crear una lista de 10 elementos

In [ ]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

transformando la lista a un array/arreglo

In [ ]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Para calcular el promedio

In [ ]:
promedio_int = np.mean(lista)
promedio_int

np.float64(5.5)

crear una lista solo de 1

In [ ]:
unos = np.ones(100)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

lista de datos compuestos

In [ ]:
arreglo_2 = ["pachi",3,5.5,True]
arreglo_2

['pachi', 3, 5.5, True]

transformando una lista compuesta en array

In [ ]:
arreglo_2 = np.array(arreglo_2)
arreglo_2

array(['pachi', '3', '5.5', 'True'], dtype='<U32')

aplicando paquetes random

In [ ]:
np.random.randint(10) #te genera un número random y su tope es 10

8

In [ ]:
np.rand() #te genera números aleatorios sin limite desde el rango del 0 al 1 ej: 0,87543

In [ ]:
np.rand(3) # El número que esta dentro del () son la cantidad de números que te genera ej:0,323; 0,4572; 0,5196

In [ ]:
#np.rand = float            arrange = arreglos
#np.randint = int           range = lista

creación de un arreglo de 10 elementos

In [ ]:
arreglo_3 = np.arange(1,11)
arreglo_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])